version: '3.1'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=tp
    volumes:
    - tp_db:/var/lib/mysql
volumes:
  tp_db:
    external: true
